#!/usr/bin/env node
// tools/notes.mjs — the build pipeline for study-notes/*.md -> assets/js/notes-data*.js
//
// Why this exists: the two generated files are single ~137KB lines each. Grepping or
// diffing them directly floods the context window. Never hand-edit them or read them
// directly — edit the .md source and run `build`. See CLAUDE.md for the full rules.
//
// Subcommands:
//   node tools/notes.mjs build        regenerate both notes-data*.js + refresh the index
//   node tools/notes.mjs check        verify the committed files match the sources (no drift)
//   node tools/notes.mjs find <term>  grep study-notes/*.md only, print compact hits
//
// Zero dependencies by design — plain Node (v18+).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const INDEX_PATH = path.join(ROOT, 'tools/notes-index.tsv');
const EN_DIR = path.join(ROOT, 'study-notes');
const UR_DIR = path.join(ROOT, 'study-notes-ur');
const EN_OUT = path.join(ROOT, 'assets/js/notes-data.js');
const UR_OUT = path.join(ROOT, 'assets/js/notes-data-ur.js');

const HEADER = [
  '// AUTO-GENERATED by tools/notes.mjs — do not hand-edit.',
  '// To update a note, edit the matching .md file in {DIR}/ and run: node tools/notes.mjs build',
];

// ---- markdown -> html -----------------------------------------------------

function inlineFmt(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
}

function lineKind(line) {
  if (/^- /.test(line)) return 'ul';
  if (/^\d+\.\s+/.test(line)) return 'ol';
  return 'p';
}

function stripMarker(line, kind) {
  if (kind === 'ul') return line.slice(2);
  if (kind === 'ol') return line.replace(/^\d+\.\s+/, '');
  return line;
}

function emitRun(kind, run, out) {
  if (!run.length) return;
  if (kind === 'p') {
    out.push(`<p>${inlineFmt(run.join(' '))}</p>`);
  } else {
    const tag = kind === 'ul' ? 'ul' : 'ol';
    const items = run.map((l) => `<li>${inlineFmt(l)}</li>`).join('');
    out.push(`<${tag}>${items}</${tag}>`);
  }
}

// Convert one note's markdown source into {title, html}.
function convert(md) {
  const lines = md.split('\n');
  let title = null;
  const out = [];
  let block = []; // raw trimmed lines of the current blank-line-separated block

  const flushBlock = () => {
    if (!block.length) return;
    // Within a block, split into runs whenever the line "kind" (ul/ol/p) changes —
    // e.g. a bullet list directly following a prose line with no blank line still
    // becomes its own <ul>, matching how these notes were originally hand-written.
    let run = [];
    let runKind = null;
    for (const raw of block) {
      const kind = lineKind(raw);
      if (runKind !== null && kind !== runKind) {
        emitRun(runKind, run, out);
        run = [];
      }
      runKind = kind;
      run.push(stripMarker(raw, kind));
    }
    emitRun(runKind, run, out);
    block = [];
  };

  for (const rawLine of lines) {
    const l = rawLine.trim();
    if (l === '') { flushBlock(); continue; }
    if (title === null && /^# /.test(l)) {
      flushBlock();
      title = l.slice(2).replace(/^\d+\.\s*/, '');
      continue;
    }
    if (/^## /.test(l)) { flushBlock(); out.push(`<h2>${inlineFmt(l.slice(3))}</h2>`); continue; }
    if (/^### /.test(l)) { flushBlock(); out.push(`<h3>${inlineFmt(l.slice(4))}</h3>`); continue; }
    block.push(l);
  }
  flushBlock();

  return { title, html: out.join('\n') };
}

// ---- index (id <-> file <-> title) -----------------------------------------

function readIndex() {
  const raw = fs.readFileSync(INDEX_PATH, 'utf8').trim().split('\n');
  const header = raw[0].split('\t');
  return raw.slice(1).map((line) => {
    const cols = line.split('\t');
    const row = {};
    header.forEach((h, i) => { row[h] = cols[i]; });
    return row;
  });
}

function writeIndex(rows) {
  const lines = ['id\ten_file\tur_file\ttitle'];
  for (const r of rows) lines.push([r.id, r.en_file, r.ur_file, r.title].join('\t'));
  fs.writeFileSync(INDEX_PATH, lines.join('\n') + '\n');
}

// ---- build ------------------------------------------------------------------

function buildOne(dir, file) {
  const md = fs.readFileSync(path.join(dir, file), 'utf8');
  return convert(md);
}

function writeDataFile(outPath, dirLabel, entries) {
  // entries: [{id, file, title, html}]
  const lines = [
    HEADER[0],
    HEADER[1].replace('{DIR}', dirLabel),
  ];
  const varName = outPath.endsWith('-ur.js') ? 'NOTES_UR' : 'NOTES';
  // One note per source line — keeps single-note diffs and greps small.
  lines.push(`const ${varName} = {`);
  entries.forEach((e, i) => {
    const obj = JSON.stringify({ title: e.title, html: e.html, file: e.file });
    const comma = i < entries.length - 1 ? ',' : '';
    lines.push(`"${e.id}":${obj}${comma}`);
  });
  lines.push('};');
  fs.writeFileSync(outPath, lines.join('\n') + '\n');
}

function build({ write = true } = {}) {
  const rows = readIndex();
  const enEntries = [];
  const urEntries = [];
  const refreshedRows = [];

  for (const row of rows) {
    const en = buildOne(EN_DIR, row.en_file);
    const ur = buildOne(UR_DIR, row.ur_file);
    enEntries.push({ id: row.id, file: row.en_file, title: en.title, html: en.html });
    urEntries.push({ id: row.id, file: row.ur_file, title: ur.title, html: ur.html });
    // Keep the title column in the index in sync with the English source's H1.
    refreshedRows.push({ ...row, title: en.title });
  }

  if (write) {
    writeDataFile(EN_OUT, 'study-notes', enEntries);
    writeDataFile(UR_OUT, 'study-notes-ur', urEntries);
    writeIndex(refreshedRows);
  }
  return { enEntries, urEntries, refreshedRows };
}

// ---- check ------------------------------------------------------------------

// Each note is one line ("id":{...}), so a line-level diff tells us exactly
// which note ids changed without ever comparing (or printing) full file bodies.
function noteLines(content) {
  const map = new Map();
  for (const line of content.split('\n')) {
    const m = line.match(/^"([^"]+)":/);
    if (m) map.set(m[1], line);
  }
  return map;
}

function reportLineDrift(label, beforeContent, afterContent) {
  const before = noteLines(beforeContent || '');
  const after = noteLines(afterContent);
  const ids = new Set([...before.keys(), ...after.keys()]);
  const changed = [];
  for (const id of ids) {
    if (before.get(id) !== after.get(id)) changed.push(id);
  }
  if (changed.length) {
    console.log(`${label}: ${changed.length} note(s) differ from committed output: ${changed.sort().join(', ')}`);
  }
  return changed.length > 0;
}

function check() {
  const before = {
    en: fs.existsSync(EN_OUT) ? fs.readFileSync(EN_OUT, 'utf8') : '',
    ur: fs.existsSync(UR_OUT) ? fs.readFileSync(UR_OUT, 'utf8') : '',
    idx: fs.existsSync(INDEX_PATH) ? fs.readFileSync(INDEX_PATH, 'utf8') : '',
  };
  build({ write: true });
  const after = {
    en: fs.readFileSync(EN_OUT, 'utf8'),
    ur: fs.readFileSync(UR_OUT, 'utf8'),
    idx: fs.readFileSync(INDEX_PATH, 'utf8'),
  };

  const enDrift = reportLineDrift('EN', before.en, after.en);
  const urDrift = reportLineDrift('UR', before.ur, after.ur);
  const idxDrift = before.idx !== after.idx;
  if (idxDrift) console.log('notes-index.tsv: refreshed (title or mapping changed)');

  if (!enDrift && !urDrift && !idxDrift) {
    console.log('OK — generated files match study-notes/*.md sources, no drift.');
    return 0;
  }
  console.log('Rebuilt to match sources. Review `git diff` and commit.');
  return 1;
}

// ---- find -------------------------------------------------------------------

function find(term) {
  if (!term) {
    console.error('usage: node tools/notes.mjs find <term>');
    return 1;
  }
  const rows = readIndex();
  const byFile = new Map();
  for (const row of rows) {
    byFile.set(path.join('study-notes', row.en_file), row.id);
    byFile.set(path.join('study-notes-ur', row.ur_file), row.id + ' (ur)');
  }
  const re = new RegExp(term, 'i');
  const hits = [];
  for (const [rel, id] of byFile) {
    const full = path.join(ROOT, rel);
    if (!fs.existsSync(full)) continue;
    const lines = fs.readFileSync(full, 'utf8').split('\n');
    lines.forEach((line, i) => {
      if (re.test(line)) {
        const snippet = line.trim().slice(0, 100);
        hits.push(`${id.padEnd(8)} │ ${rel}:${i + 1} │ ${snippet}`);
      }
    });
    if (hits.length >= 30) break;
  }
  if (!hits.length) {
    console.log(`No matches for "${term}" in study-notes/ or study-notes-ur/.`);
    return 0;
  }
  console.log(hits.slice(0, 30).join('\n'));
  if (hits.length >= 30) console.log('… capped at 30 hits, refine your term.');
  return 0;
}

// ---- entry --------------------------------------------------------------------

const [, , cmd, ...rest] = process.argv;
switch (cmd) {
  case 'build':
    build({ write: true });
    console.log('Built assets/js/notes-data.js, assets/js/notes-data-ur.js, tools/notes-index.tsv');
    break;
  case 'check':
    process.exitCode = check();
    break;
  case 'find':
    process.exitCode = find(rest.join(' '));
    break;
  default:
    console.error('usage: node tools/notes.mjs <build|check|find> [term]');
    process.exitCode = 1;
}
